### ISSUE TITLE
failed on centos 7.7

### ISSUE THREAD

**Issue by ossiemarks** [AcroMedia/ansible-role-nfs#1]
TASK [acromedia.nfs/server : Install NFS utilities] ****************************************************************************************
fatal: [master.devopscomputing.co.uk]: FAILED! => {"changed": false, "msg": "No package matching 'nfs-utils-lib' found available, installed or updated", "rc": 126, "results": ["1:nfs-utils-1.3.0-0.65.el7.x86_64 providing nfs-utils is already installed", "No package matching 'nfs-utils-lib' found available, installed or updated"]}

**Comment by dale-c-anderson** [comment]
@ossiemarks thanks for the feedback. The role has only been tested with CentOS 6.

For centos 7, you should be able to just comment out that lib package from the red hat tasks file https://github.com/AcroMedia/ansible-role-nfs/blob/master/server/tasks/RedHat.yml#L6 to get your copy working.

**Comment by ossiemarks** [comment]
Thanks for feeding back, yes the two packages are now combined so if Os = 7.7 just install nfs-utlils and not nfs-utils-libs

Thanks :)

**Comment by dale-c-anderson** [comment]
This should be fixed as of https://github.com/AcroMedia/ansible-role-nfs/commit/d2a1f5b2c4cb2e268fe01cb47d615d5f716ea450
